title: Data Science by Stacy
author:Stacy Keago
email: https://stacykeago.github.io/
description: > # this means to ignore newlines until "baseurl:"
  A Data Science story.

# social links
twitter_username: coding_chic_stacy # DO NOT include the @ character, or else the build will fail!
github_username:  stacykeago # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima

